version: "3.7"
services:
    ectf_scrape:
        container_name: ectf_scrape_bot
        build:
            dockerfile: ./Dockerfile
            context: ../scrape-bot
        ports:
            - "8080:8080"
            - "8081:8081"
        restart: always
